---
name: CGI-Application-Plugin-ProtectCSRF
version: 1
author:
  - 'Akira Horimoto <kurt0027@gmail.com>'
abstract: Plug-in protected from CSRF
license: perl
requires:
  Attribute::Handlers: 0.78
  CGI::Application: 4.04
  CGI::Application::Plugin::Session: 1.01
  Digest::SHA1: 2.07
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  license: http://dev.perl.org/licenses/
